Repository RoboJackets/robocup-software, pull requests merged in 2018-08, with the labels that each got.

#1195 Added simple summary of plays, skills, tactics to docs
  doc/PlaysTacticsSkillsSummary.md
Labels: area / support, exp / adept (2), priority / wishlist, status / code-review, type / enhancement

#1172 Remove Model reset from play reloading
  soccer/gameplay/main.py
  soccer/gameplay/play_registry.py
Labels: area / ui, exp / adept (2), priority / low, status / code-review, type / bug

#1167 Clamp dribbler speed to max before sending to firmware
  common/Constants.hpp
  soccer/Processor.cpp
  soccer/Robot.cpp
  soccer/Robot.hpp
Labels: area / soccer, exp / adept (2), priority / medium, status / ready-for-merge, type / new feature
