Repository RoboJackets/robocup-software, pull requests merged in 2019-08, with the labels that each got.

#1259 Update for Ubuntu 19.04
  soccer/CMakeLists.txt
  util/ubuntu-packages.txt
  util/ubuntu-setup
Labels: area / support, exp / adept (2), priority / low, status / code-review, type / bug, warn / not ready

#1311 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: area / support, priority / medium, status / code-review

#1292 Switched aiming from goal center to use window evaluator
  soccer/gameplay/plays/restarts/our_shootout_kick.py
Labels: area / plays, exp / adept (2), priority / low, status / code-review, type / enhancement

#1316 Make Pose and Twist operator<< friend and fix typo
  common/Geometry2d/Pose.hpp
  common/Geometry2d/PoseTest.cpp
Labels: area / support, exp / novice (1), priority / medium, type / bug
