Repository RoboJackets/robocup-software, pull requests merged in 2020-02, with the labels that each got.

#1403 Fix segfault when clicking on field when running real robots
  soccer/Context.hpp
  soccer/Processor.cpp
  soccer/ui/MainWindow.cpp
  soccer/ui/SimFieldView.cpp
Labels: area / ui, priority / high, status / code-review, type / bug

#1396 Basic defensive scramble
  soccer/gameplay/playbooks/SituationalTestingBook.pbk
  soccer/gameplay/plays/Defend_Goal/winger_wall.py
  soccer/gameplay/plays/Defensive_Scramble/__init__.py
  soccer/gameplay/plays/Defensive_Scramble/basic_defensive_scramble.py
Labels: area / plays, exp / adept (2), priority / medium, status / code-review, type / enhancement

#1417 Remove gap in wall tactics
  soccer/gameplay/tactics/wall.py
Labels: area / plays, exp / adept (2), priority / medium, status / code-review, type / bug
